### PR TITLE
fix: stuck initialization on iPhone Simulator

### PR DESCRIPTION
**Pull request by ekasetiawans**
fix for #5

### CODE REVIEW

**Comment by ekasetiawans** [comment]
hi @mrcendre can you review this?

**Review by mrcendre — APPROVED** [review]
Awesome, thank you very much @ekasetiawans !

</img>

**Comment by ekasetiawans** [comment]
Now, I'm waiting to be published in pub.dev @mrcendre 😄 
Btw, you are amazing making this package

**Comment by mrcendre** [comment]
There you go, 1.3.3 is now available on pub.dev 👌
Much too kind, I'm really stoked you like it. Thanks again for your contribution !

**Pull request merged**
